# Owner task: EB-18 Docker Compose dev stack
"""Generate deploy/.env.dev with random development secrets (never committed; .gitignore covers .env.*).

Refuses to overwrite an existing file unless --force, so a running stack's passwords are not changed under it.
"""

from __future__ import annotations

import argparse
import os
import secrets
import sys
from pathlib import Path

DEFAULT_PATH = Path(__file__).resolve().parents[2] / "deploy" / ".env.dev"
SECRETS = [
    "POSTGRES_SUPERUSER_PASSWORD", "KLARITY_ADMIN_PASSWORD", "KLARITY_APP_PASSWORD", "KLARITY_CONTROL_PASSWORD",
    "INFRA_DB_PASSWORD", "KEYCLOAK_ADMIN_PASSWORD", "KEYCLOAK_WEB_CLIENT_SECRET", "OPENFGA_PRESHARED_KEY",
    "QDRANT_API_KEY", "VALKEY_PASSWORD",
]


def render() -> str:
    lines = ["# Generated by ops/dev/gen_env.py — local development only, never commit."]
    lines += [f"{name}={secrets.token_urlsafe(24)}" for name in SECRETS]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--path", type=Path, default=DEFAULT_PATH)
    ap.add_argument("--force", action="store_true", help="overwrite an existing file (changes all passwords)")
    args = ap.parse_args(argv)
    if args.path.exists() and not args.force:
        print(f"{args.path} already exists; keeping it (use --force to regenerate)")
        return 0
    args.path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(args.path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as fh:
        fh.write(render())
    os.chmod(args.path, 0o600)
    print(f"wrote {args.path} (mode 600)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
