"""Generate docs/borrow/BORROW_MAP.md from the Borrow Register snapshot and third_party/*/UPSTREAM.yaml.

Owner task: EB-76 Licence verdicts and Borrow Register sign-off
Usage: python ops/ci/borrow_map.py [--check]   (--check fails if BORROW_MAP.md is stale)
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from vendor_upstream import MANIFESTS  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
REGISTER = REPO / "docs/borrow/borrow-register.json"
OUT = REPO / "docs/borrow/BORROW_MAP.md"

# Adopted runtime dependencies -> where they are wired in, and the owning task.
DEPENDENCY_TARGETS = {
    "Docling": ("services/normalization/parsers/", "EB-30"),
    "ezdxf": ("packs/aec/cad/", "EB-35"),
    "Langfuse": ("packages/observability/, services/llm-gateway/", "EB-26"),
    "OpenFGA": ("packages/permissions/", "EB-22"),
    "Temporal (+ samples-python)": ("services/ingestion/workflows/", "EB-29"),
}
REVIEW_STATES = {"pending": "vendored, review pending", "in-review": "in review",
                 "adapted": "adapted into target", "dropped": "dropped"}


def feature_rows(tool: str) -> list[tuple[str, str, str, int, str]]:
    manifest = (REPO / "third_party" / tool / "UPSTREAM.yaml").read_text()
    rows = []
    for fid, body in re.findall(r"^  ([\w-]+):\n((?:    .*\n)+)", manifest, re.M):
        task = re.search(r"task: (\S+)", body).group(1)
        target = re.search(r"target: (.+)", body).group(1)
        review = re.search(r"review: (\S+)", body).group(1)
        n = len(re.findall(r"- \{path:", body))
        rows.append((fid, task, target, n, REVIEW_STATES.get(review, review)))
    return rows


def render() -> str:
    reg = json.loads(REGISTER.read_text())
    tools = reg["tools"]
    by = lambda d, v: [t for t in tools if t["decision"] == d and (v is None or t["verdict"] == v)]  # noqa: E731
    out = [
        "# Borrow Map",
        "",
        "> Owner task: EB-76 Licence verdicts and Borrow Register sign-off  ",
        f"> Generated by `ops/ci/borrow_map.py` from `docs/borrow/borrow-register.json` "
        f"(Notion snapshot {reg['_snapshot']}). Do not edit by hand.",
        "",
        "How code moves from an upstream tool into K!larity:",
        "",
        "1. **Vendor** — `ops/ci/vendor_upstream.py` copies only Adopt + Copy-with-attribution features, "
        "at a pinned commit, refusing `ee/`/`enterprise/` paths and banned files, into `third_party/<tool>/src/` "
        "with SHA-256 per file. Vendored files are never edited in place (CI enforces this).",
        "2. **Review** — read the vendored feature against the owning EB task; decide keep / rewrite / drop.",
        "3. **Adapt** — write K!larity code in the target path (tenant_id at every boundary, typed + versioned "
        "interfaces, no plaintext secrets), with a `Borrowed from:` line naming tool, commit and file.",
        "4. **Record** — set the feature's `review:` state in `UPSTREAM.yaml` and add the notice to "
        "`THIRD_PARTY_NOTICES.md`.",
        "",
        f"Register totals: {len(tools)} tools — "
        + ", ".join(f"{d}: {len(by(d, None))}" for d in ("Adopt", "Borrow pattern", "To review", "Reject")),
        "",
        "## 1. Code vendored (Adopt + Copy with attribution)",
        "",
    ]
    for t in by("Adopt", "Copy with attribution"):
        key = t["repo"].rstrip("/").rsplit("/", 1)[-1].lower()
        m = MANIFESTS[key]
        out += [f"### {t['tool']} — `{m['commit'][:10]}` — {m['licence']}", "",
                f"Caveat: {t['caveat']}", "",
                "| Feature | Task | Target path | Files | Review state |",
                "|---|---|---|---:|---|"]
        out += [f"| {f} | {task} | `{tgt}` | {n} | {st} |" for f, task, tgt, n, st in feature_rows(key)]
        out.append("")
    out += ["## 2. Runtime dependencies (Adopt + Dependency OK)", "",
            "Installed as packages when the owning task starts — no source is copied.", "",
            "| Tool | Licence | Wired into | Task | Caveat |", "|---|---|---|---|---|"]
    for t in by("Adopt", "Dependency OK"):
        tgt, task = DEPENDENCY_TARGETS.get(t["tool"], ("unassigned", "—"))
        out.append(f"| {t['tool']} | {t['licence']} | `{tgt}` | {task} | {t['caveat'] or ''} |")
    out += ["", "## 3. Patterns only (read, never copy)", "",
            "Upstream clones are read at a pinned commit; notes go in `docs/borrow/patterns/<tool>.md`.", "",
            "| Tool | Licence | What to borrow | Caveat |", "|---|---|---|---|"]
    for t in by("Borrow pattern", None):
        out.append(f"| {t['tool']} | {t['licence']} | {t['borrow']} | {t['caveat'] or ''} |")
    out += ["", "## 4. Awaiting decision (To review — no code or dependency until EB-76 sign-off)", "",
            "| Tool | Verdict | Module | What to borrow |", "|---|---|---|---|"]
    for t in sorted(by("To review", None), key=lambda t: (t["verdict"], t["tool"])):
        out.append(f"| {t['tool']} | {t['verdict']} | {t['module']} | {t['borrow']} |")
    out += ["", "## 5. Rejected", "", "| Tool | Reason |", "|---|---|"]
    out += [f"| {t['tool']} | {t['caveat']} |" for t in by("Reject", None)]
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit("docs/borrow/BORROW_MAP.md is stale — run `make borrow-map`")
        print("borrow map up to date")
    else:
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(REPO)}")
